"""hook-setup: Install git hooks and .claude-wiki/ wrapper in the target repo.

Run this manually after init. Each hook stage can be skipped with a flag.

Stages:
  0. .claude-wiki/  — drop wrapper script + llm.md symlink, add to .gitignore
  1. pre-commit     — on every commit, logs changed source files to drift.jsonl (non-blocking)
  2. post-checkout  — after clone or branch switch, creates missing docs and symlinks
  3. skip-worktree  — tells git to ignore CLAUDE.md symlinks so they never appear as changes

Hooks call .claude-wiki/wiki to invoke the wiki CLI. The wrapper resolves the wiki
root from the .claude-wiki/llm.md symlink — no separate config file needed.
"""

import os
import stat
import subprocess

from .lib import (
    CONFLICT_LOG, DRIFT_LOG, FLAGS_FILE, INSTRUCTIONS_FILE, NEW_ENTRY_LOG,
    SCHEMA_FILE, TEMPLATE_FILE, WIKI_ROOT, WIKI_MERGE_FILE, WIKI_UPDATE_FILE,
    get_repo_path, load_schema, symlink_path, walk_schema,
)


_WRAPPER_SCRIPT = """\
#!/usr/bin/env bash
# claude-wiki wrapper — auto-generated by claude-wiki hook-setup. Do not edit.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WIKI="$(cat "$SCRIPT_DIR/wiki-path")"
cd "$WIKI" && exec claude-wiki "$@"
"""

_PRE_COMMIT = """\
#!/usr/bin/env bash
# claude-wiki: log changed source files to drift.jsonl before each commit.
# Non-blocking — exits 0 regardless so it never prevents commits.
ROOT=$(git rev-parse --show-toplevel)
"$ROOT/.claude-wiki/wiki" detect-drift --staged 2>/dev/null || true
exit 0
"""

_POST_CHECKOUT = """\
#!/usr/bin/env bash
# claude-wiki: create missing docs and symlinks after clone or branch switch.
ROOT=$(git rev-parse --show-toplevel)
"$ROOT/.claude-wiki/wiki" push 2>/dev/null || true
exit 0
"""


def _setup_claude_wiki_dir(repo):
    cw_dir = repo / ".claude-wiki"
    cw_dir.mkdir(exist_ok=True)

    # Wiki path file — read by the wrapper script to locate the wiki root
    (cw_dir / "wiki-path").write_text(str(WIKI_ROOT) + "\n")
    print(f"  [written]  .claude-wiki/wiki-path  ({WIKI_ROOT})")

    # Wrapper script
    wrapper = cw_dir / "wiki"
    wrapper.write_text(_WRAPPER_SCRIPT)
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Symlink to wiki's flags.json — exposes wiki status to agents in the target repo
    flags_link = cw_dir / "flags.json"
    if flags_link.exists() or flags_link.is_symlink():
        flags_link.unlink()
    rel_flags = os.path.relpath(FLAGS_FILE, cw_dir)
    flags_link.symlink_to(rel_flags)

    # Symlink to wiki's schema.yaml — allows editing from the target repo
    schema_link = cw_dir / "schema.yaml"
    if schema_link.exists() or schema_link.is_symlink():
        schema_link.unlink()
    rel_schema = os.path.relpath(SCHEMA_FILE, cw_dir)
    schema_link.symlink_to(rel_schema)

    # Symlinks to operational files in .claude-wiki/ root
    for src, name in [
        (TEMPLATE_FILE,     "CLAUDE.template.md"),
        (INSTRUCTIONS_FILE, "instructions.md"),
        (DRIFT_LOG,         "drift.jsonl"),
        (NEW_ENTRY_LOG,     "new-entry.jsonl"),
        (CONFLICT_LOG,      "conflict.jsonl"),
    ]:
        link = cw_dir / name
        if link.exists() or link.is_symlink():
            link.unlink()
        if src.exists():
            rel = os.path.relpath(src, cw_dir)
            link.symlink_to(rel)
            print(f"  [symlink]  .claude-wiki/{name} -> {rel}")

    # agents/ subdirectory — LLM guidance docs
    agents_dir = cw_dir / "agents"
    agents_dir.mkdir(exist_ok=True)

    llm_target = WIKI_ROOT / "llm.md"
    rel_llm = os.path.relpath(llm_target, agents_dir)
    for src, name in [
        (llm_target,       "llm.md"),
        (WIKI_UPDATE_FILE, "WIKI_UPDATE.md"),
        (WIKI_MERGE_FILE,  "WIKI_MERGE.md"),
    ]:
        link = agents_dir / name
        if link.exists() or link.is_symlink():
            link.unlink()
        if src.exists():
            rel = os.path.relpath(src, agents_dir)
            link.symlink_to(rel)
            print(f"  [symlink]  .claude-wiki/agents/{name} -> {rel}")

    # Add .claude-wiki to .gitignore
    gitignore = repo / ".gitignore"
    entry = ".claude-wiki"
    if gitignore.exists():
        content = gitignore.read_text()
        if entry not in content:
            gitignore.write_text(content.rstrip() + "\n\n# claude-wiki\n.claude-wiki\n")
            print(f"  [gitignore] .claude-wiki added to .gitignore")
    else:
        gitignore.write_text("# claude-wiki\n.claude-wiki\n")
        print(f"  [created]  .gitignore  (with .claude-wiki entry)")

    print(f"  [created]  .claude-wiki/wiki  (wrapper script)")
    print(f"  [symlink]  .claude-wiki/flags.json -> {rel_flags}")
    print(f"  [symlink]  .claude-wiki/schema.yaml -> {rel_schema}")
    print(f"  [dir]      .claude-wiki/agents/")


def run_hook_setup(
    pre_commit: bool = True,
    post_checkout: bool = True,
    skip_worktree: bool = True,
):
    repo = get_repo_path()
    git_dir = repo / ".git"

    if not git_dir.exists():
        raise SystemExit(f"No .git directory found in {repo}")

    # Always set up .claude-wiki/ — hooks depend on it
    _setup_claude_wiki_dir(repo)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)


    if pre_commit:
        hook = hooks_dir / "pre-commit"
        if hook.exists() and "claude-wiki" not in hook.read_text():
            print(f"  [skipped]  pre-commit  (existing hook not owned by claude-wiki — edit manually)")
        else:
            hook.write_text(_PRE_COMMIT)
            hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"  [written]  .git/hooks/pre-commit  (detect-drift on each commit)")
    else:
        print("  [skipped]  pre-commit")

    if post_checkout:
        hook = hooks_dir / "post-checkout"
        if hook.exists() and "claude-wiki" not in hook.read_text():
            print(f"  [skipped]  post-checkout  (existing hook not owned by claude-wiki — edit manually)")
        else:
            hook.write_text(_POST_CHECKOUT)
            hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"  [written]  .git/hooks/post-checkout  (push after checkout)")
    else:
        print("  [skipped]  post-checkout")

    if skip_worktree:
        schema = load_schema()
        nodes = walk_schema(schema)
        count = 0
        for rel_path, _ in nodes:
            link = symlink_path(repo, rel_path)
            if link.exists() or link.is_symlink():
                subprocess.run(
                    ["git", "-C", str(repo), "update-index", "--skip-worktree",
                     str(link.relative_to(repo))],
                    capture_output=True,
                )
                count += 1
        print(f"  [done]     skip-worktree on {count} CLAUDE.md symlink(s)")
    else:
        print("  [skipped]  skip-worktree")
